namespace RadarSoft.RadarCube.Serialization
{
    /// <exclude />
    internal enum Tags
    {
        tgStep = 256,
        tgLast = tgStep - 1,

        tgList = tgStep * 0,
        tgList_Count = tgList + 1,
        tgList_ItemType = tgList + 2,
        tgList_Item = tgList + 3,
        tgList_EOT = tgList + tgLast,

        tgDataColumn = tgStep * 10,
        tgDataColumn_DataType = tgDataColumn + 1,
        tgDataColumn_ColumnName = tgDataColumn + 2,
        tgDataColumn_Caption = tgDataColumn + 3,
        tgDataColumn_SourceColumnName = tgDataColumn + 4,
        tgDataColumn_SourceColumnFormat = tgDataColumn + 5,
        tgDataColumn_Calculated = tgDataColumn + 6,
        tgDataColumn_Size = tgDataColumn + 7,
        tgDataColumn_BIType = tgDataColumn + 8,
        tgDataColumn_IsBLOB = tgDataColumn + 9,
        tgDataColumn_EOT = tgDataColumn + tgLast,

        tgDataIndex = tgStep * 11,
        tgDataIndex_IndexName = tgDataIndex + 1,
        tgDataIndex_Ordinal = tgDataIndex + 2,
        tgDataIndex_KeyColumn = tgDataIndex + 3,
        tgDataIndex_Stream = tgDataIndex + 4,
        tgDataIndex_EOT = tgDataIndex + tgLast,

        tgDataRelation = tgStep * 12,
        tgDataRelation_RelationName = tgDataRelation + 1,
        tgDataRelation_ChildTable = tgDataRelation + 2,
        tgDataRelation_ParentTable = tgDataRelation + 3,
        tgDataRelation_ChildColumns = tgDataRelation + 4,
        tgDataRelation_ParentColumns = tgDataRelation + 5,
        tgDataRelation_EOT = tgDataRelation + tgLast,

        tgDataTable = tgStep * 13,
        tgDataTable_TableName = tgDataTable + 1,
        tgDataTable_OriginalTable = tgDataTable + 2,
        tgDataTable_Columns = tgDataTable + 3,
        tgDataTable_Indexes = tgDataTable + 4,
        tgDataTable_SelfRelationColumn = tgDataTable + 5,
        tgDataTable_DbStreamSize = tgDataTable + 6,
        tgDataTable_IncludeStreams = tgDataTable + 7,
        tgDataTable_DbStream = tgDataTable + 8,
        tgDataTable_MemoStream = tgDataTable + 9,
        tgDataTable_UsedInCube = tgDataTable + 10,
        tgDataTable_LevelsCount = tgDataTable + 11,
        tgDataTable_EOT = tgDataTable + tgLast,

        tgDataSet = tgStep * 14,
        tgDataSet_WorkingDirectory = tgDataSet + 1,
        tgDataSet_Tables = tgDataSet + 2,
        tgDataSet_Relations = tgDataSet + 3,
        tgDataSet_EOT = tgDataSet + tgLast,

        tgWorkingDirectory = tgStep * 15,
        tgWorkingDirectory_UseSystemTemp = tgWorkingDirectory + 1,
        tgWorkingDirectory_CustomDirectory = tgWorkingDirectory + 2,
        tgWorkingDirectory_RandomDirectory = tgWorkingDirectory + 3,
        tgWorkingDirectory_EOT = tgWorkingDirectory + tgLast,

        tgInternalFactTable = tgStep * 16,
        tgInternalFactTable_RecordCount = tgInternalFactTable + 1,
        tgInternalFactTable_LevelCount = tgInternalFactTable + 2,
        tgInternalFactTable_MeasureCount = tgInternalFactTable + 3,
        tgInternalFactTable_Row = tgInternalFactTable + 4,
        tgInternalFactTable_DateCount = tgInternalFactTable + 5,
        tgInternalFactTable_EOT = tgInternalFactTable + tgLast,

        tgPermanentCubeData = tgStep * 17,
        tgPermanentCubeData_Guid = tgPermanentCubeData + 1,
        tgPermanentCubeData_Dataset = tgPermanentCubeData + 2,
        tgPermanentCubeData_InternalFactTable = tgPermanentCubeData + 3,
        tgPermanentCubeData_FactTableName = tgPermanentCubeData + 4,
        tgPermanentCubeData_EOT = tgPermanentCubeData + tgLast,

        tgVariableCubeData = tgStep * 18,
        tgVariableCubeData_Dimensions = tgVariableCubeData + 1,
        tgVariableCubeData_Measures = tgVariableCubeData + 2,
        tgVariableCubeData_LevelsList = tgVariableCubeData + 3,
        tgVariableCubeData_Active = tgVariableCubeData + 4,
        tgVariableCubeData_EOT = tgVariableCubeData + tgLast,

        tgInfoAttribute = tgStep * 19,
        tgInfoAttribute_SourceField = tgInfoAttribute + 1,
        tgInfoAttribute_DisplayName = tgInfoAttribute + 2,
        tgInfoAttribute_UniqueName = tgInfoAttribute + 3,
        tgInfoAttribute_Description = tgInfoAttribute + 4,
        tgInfoAttribute_FieldType = tgInfoAttribute + 5,
        tgInfoAttribute_DisplayMode = tgInfoAttribute + 6,
        tgInfoAttribute_EOT = tgInfoAttribute + tgLast,

        tgCubeLevel = tgStep * 20,
        tgCubeLevel_FirstLevelMembersCount = tgCubeLevel + 1,
        tgCubeLevel_DisplayName = tgCubeLevel + 2,
        tgCubeLevel_UniqueName = tgCubeLevel + 3,
        tgCubeLevel_Description = tgCubeLevel + 4,
        tgCubeLevel_MDXLevelIndex = tgCubeLevel + 5,
        tgCubeLevel_MembersCount = tgCubeLevel + 6,
        tgCubeLevel_LevelType = tgCubeLevel + 7,
        tgCubeLevel_FormatString = tgCubeLevel + 8,
        tgCubeLevel_SourceHierarchy = tgCubeLevel + 9,
        tgCubeLevel_FetchedCount = tgCubeLevel + 10,
        tgCubeLevel_ID = tgCubeLevel + 11,
        tgCubeLevel_InfoAttributeName = tgCubeLevel + 12,
        tgCubeLevel_BIMembersType = tgCubeLevel + 13,
        tgCubeLevel_InfoAttributeClass = tgCubeLevel + 14,
        tgCubeLevel_EOT = tgCubeLevel + tgLast,

        tgCubeHierarchy = tgStep * 21,
        tgCubeHierarchy_ChildrenCount = tgCubeHierarchy + 1,
        tgCubeHierarchy_NextLevelChildrenCount = tgCubeHierarchy + 2,
        tgCubeHierarchy_LeafMember = tgCubeHierarchy + 3,
        tgCubeHierarchy_Origin = tgCubeHierarchy + 4,
        tgCubeHierarchy_DisplayName = tgCubeHierarchy + 5,
        tgCubeHierarchy_UniqueName = tgCubeHierarchy + 6,
        tgCubeHierarchy_Description = tgCubeHierarchy + 7,
        tgCubeHierarchy_TotalCaption = tgCubeHierarchy + 8,
        tgCubeHierarchy_DisplayField = tgCubeHierarchy + 9,
        tgCubeHierarchy_ParentField = tgCubeHierarchy + 10,
        tgCubeHierarchy_IDField = tgCubeHierarchy + 11,
        tgCubeHierarchy_TypeOfMembers = tgCubeHierarchy + 12,
        tgCubeHierarchy_InfoAttributes = tgCubeHierarchy + 13,
        tgCubeHierarchy_CalculatedByRows = tgCubeHierarchy + 14,
        tgCubeHierarchy_Children = tgCubeHierarchy + 15,
        tgCubeHierarchy_FormatString = tgCubeHierarchy + 16,
        tgCubeHierarchy_MDXLevelNames = tgCubeHierarchy + 17,
        tgCubeHierarchy_DescriptionField = tgCubeHierarchy + 18,
        tgCubeHierarchy_DisplayFieldType = tgCubeHierarchy + 19,
        tgCubeHierarchy_ParentFieldType = tgCubeHierarchy + 20,
        tgCubeHierarchy_IDFieldType = tgCubeHierarchy + 21,
        tgCubeHierarchy_DisplayFolder = tgCubeHierarchy + 22,
        tgCubeHierarchy_DataTable = tgCubeHierarchy + 23,
        tgCubeHierarchy_MembersWithData = tgCubeHierarchy + 24,
        tgCubeHierarchy_MemberIsNull = tgCubeHierarchy + 25,
        tgCubeHierarchy_UnknownMemberName = tgCubeHierarchy + 26,
        tgCubeHierarchy_DiscretizationMethod = tgCubeHierarchy + 27,
        tgCubeHierarchy_DiscretizationBucketCount = tgCubeHierarchy + 28,
        tgCubeHierarchy_DiscretizationBucketFormat = tgCubeHierarchy + 29,
        tgCubeHierarchy_Alignment = tgCubeHierarchy + 30,
        tgCubeHierarchy_HierarchyAppearance = tgCubeHierarchy + 31,
        tgCubeHierarchy_TotalAppearance = tgCubeHierarchy + 32,
        tgCubeHierarchy_DenyResort = tgCubeHierarchy + 33,
        tgCubeHierarchy_DenyChangeTotalAppearance = tgCubeHierarchy + 34,
        tgCubeHierarchy_DenyRegroup = tgCubeHierarchy + 35,
        tgCubeHierarchy_DenyFilter = tgCubeHierarchy + 36,
        tgCubeHierarchy_DenyPopupOnCaptions = tgCubeHierarchy + 37,
        tgCubeHierarchy_DenyPopupOnLabels = tgCubeHierarchy + 38,
        tgCubeHierarchy_DenyHierarchyEditor = tgCubeHierarchy + 39,
        tgCubeHierarchy_DenySwapMembers = tgCubeHierarchy + 40,
        tgCubeHierarchy_NotVisible = tgCubeHierarchy + 41,
        tgCubeHierarchy_NotTakeFiltersIntoCalculations = tgCubeHierarchy + 42,
        tgCubeHierarchy_ShowEmptyLines = tgCubeHierarchy + 43,
        tgCubeHierarchy_BIType = tgCubeHierarchy + 44,
        tgCubeHierarchy_Levels = tgCubeHierarchy + 45,
        tgCubeHierarchy_MembersStream = tgCubeHierarchy + 46,
        tgCubeHierarchy_BaseNamedSetHierarchies = tgCubeHierarchy + 47,
        tgCubeHierarchy_DefaultMember = tgCubeHierarchy + 48,
        tgCubeHierarchy_EOT = tgCubeHierarchy + tgLast,

        tgCubeMember = tgStep * 22,
        tgCubeMember_DisplayName = tgCubeMember + 1,
        tgCubeMember_UniqueName = tgCubeMember + 2,
        tgCubeMember_ShortName = tgCubeMember + 3,
        tgCubeMember_Parent = tgCubeMember + 4,
        tgCubeMember_Description = tgCubeMember + 5,
        tgCubeMember_Ragged = tgCubeMember + 6,
        tgCubeMember_ID = tgCubeMember + 7,
        tgCubeMember_StringID = tgCubeMember + 8,
        tgCubeMember_StringParentID = tgCubeMember + 9,
        tgCubeMember_HideSystemGeneratedMember = tgCubeMember + 10,
        tgCubeMember_Rank = tgCubeMember + 11,
        tgCubeMember_LevelIndex = tgCubeMember + 12,
        tgCubeMember_IsTotal = tgCubeMember + 13,
        tgCubeMember_BIDate = tgCubeMember + 14,
        tgCubeMember_InfoAttributes = tgCubeMember + 15,
        tgCubeMember_IsLeaf = tgCubeMember + 16,
        tgCubeMember_ChildrenCount = tgCubeMember + 17,
        tgCubeMember_IsMDXCalculated = tgCubeMember + 18,
        tgCubeMember_Bytes = tgCubeMember + 19,
        tgCubeMember_EOT = tgCubeMember + tgLast,

        tgMember = tgStep * 23,
        tgMember_UniqueName = tgMember + 1,
        tgMember_DisplayName = tgMember + 2,
        tgMember_ShortName = tgMember + 3,
        tgMember_Description = tgMember + 4,
        tgMember_MemberType = tgMember + 5,
        tgMember_Rank = tgMember + 6,
        tgMember_Visible = tgMember + 7,
        tgMember_Depth = tgMember + 8,
        tgMember_VirtualID = tgMember + 9,
        tgMember_ParentUniqueName = tgMember + 10,
        tgMember_Children = tgMember + 11,
        tgMember_Filtered = tgMember + 50,
        tgMember_EOT = tgMember + tgLast,

        tgCalculatedMember = tgStep * 24,
        tgCalculatedMember_Position = tgCalculatedMember + 1,
        tgCalculatedMember_Expresion = tgCalculatedMember + 2,
        tgCalculatedMember_Inherited = tgCalculatedMember + 3,
        tgCalculatedMember_EOT = tgCalculatedMember + tgLast,

        tgGroupMember = tgStep * 25,
        tgGroupMember_Position = tgGroupMember + 1,
        tgGroupMember_Deleteable = tgGroupMember + 2,
        tgGroupMember_Inherited = tgGroupMember + 3,
        tgGroupMember_EOT = tgGroupMember + tgLast,

        tgHierarchy = tgStep * 26,
        tgHierarchy_UniqueMembersCount = tgHierarchy + 1,
        tgHierarchy_ChildrenCount = tgHierarchy + 2,
        tgHierarchy_NextLevelChildrenCount = tgHierarchy + 3,
        tgHierarchy_LeafMember = tgHierarchy + 4,
        tgHierarchy_StaticMembersCount = tgHierarchy + 5,
        tgHierarchy_StaticMember = tgHierarchy + 6,
        tgHierarchy_VirtualMember = tgHierarchy + 7,
        tgHierarchy_UniqueName = tgHierarchy + 31,
        tgHierarchy_Alignment = tgHierarchy + 32,
        tgHierarchy_DenyChangeTotalAppearance = tgHierarchy + 33,
        tgHierarchy_DenyFilter = tgHierarchy + 34,
        tgHierarchy_DenyHierarchyEditor = tgHierarchy + 35,
        tgHierarchy_DenyPopupOnCaptions = tgHierarchy + 36,
        tgHierarchy_DenyPopupOnLabels = tgHierarchy + 37,
        tgHierarchy_DenyRegroup = tgHierarchy + 38,
        tgHierarchy_DenyResort = tgHierarchy + 39,
        tgHierarchy_DenySwapMembers = tgHierarchy + 40,
        tgHierarchy_DisplayName = tgHierarchy + 41,
        tgHierarchy_Filtered = tgHierarchy + 42,
        tgHierarchy_FormatString = tgHierarchy + 43,
        tgHierarchy_Apearance = tgHierarchy + 44,
        tgHierarchy_Initialized = tgHierarchy + 45,
        tgHierarchy_Intelligence = tgHierarchy + 46,
        tgHierarchy_Levels = tgHierarchy + 47,
        tgHierarchy_OverrideSortMethods = tgHierarchy + 48,
        tgHierarchy_ShowEmptyLines = tgHierarchy + 49,
        tgHierarchy_SortType = tgHierarchy + 50,
        tgHierarchy_NotTakeFiltersIntoCalculations = tgHierarchy + 51,
        tgHierarchy_TotalAppearance = tgHierarchy + 52,
        tgHierarchy_TotalCaption = tgHierarchy + 53,
        tgHierarchy_NotUnfetchedMembersVisibility = tgHierarchy + 54,
        tgHierarchy_NotVisible = tgHierarchy + 55,
        tgHierarchy_MembersStream = tgHierarchy + 56,
        tgHierarchy_DenyMultiselect = tgHierarchy + 57,
        tgHierarchy_EOT = tgHierarchy + tgLast,

        tgDataRow = tgStep * 27,
        tgDataRow_Ignore = tgDataRow + 1,
        tgDataRow_NonLeafData = tgDataRow + 2,
        tgDataRow_Data = tgDataRow + 3,
        tgDataRow_EOT = tgDataRow + tgLast,

        tgCubeMeasure = tgStep * 28,
        tgCubeMeasure_DisplayName = tgCubeMeasure + 1,
        tgCubeMeasure_DisplayFolder = tgCubeMeasure + 2,
        tgCubeMeasure_Expression = tgCubeMeasure + 3,
        tgCubeMeasure_UniqueName = tgCubeMeasure + 4,
        tgCubeMeasure_Description = tgCubeMeasure + 5,
        tgCubeMeasure_DefaultFormat = tgCubeMeasure + 6,
        tgCubeMeasure_IsKPI = tgCubeMeasure + 7,
        tgCubeMeasure_KPIStatusImageIndex = tgCubeMeasure + 8,
        tgCubeMeasure_AggregateFunction = tgCubeMeasure + 9,
        tgCubeMeasure_CalculatedByRows = tgCubeMeasure + 10,
        tgCubeMeasure_SourceField = tgCubeMeasure + 11,
        tgCubeMeasure_FieldType = tgCubeMeasure + 12,
        tgCubeMeasure_DataTable = tgCubeMeasure + 13,
        tgCubeMeasure_Visible = tgCubeMeasure + 14,
        tgCubeMeasure_MeasureID = tgCubeMeasure + 15,
        tgCubeMeasure_NotVisibleInTree = tgCubeMeasure + 16,
        tgCubeMeasure_EOT = tgCubeMeasure + tgLast,

        tgLevel = tgStep * 81,
        tgLevel_Depth = tgLevel + 1,
        tgLevel_Filters = tgLevel + 2,
        tgLevel_Index = tgLevel + 3,
        tgLevel_PagerSettings = tgLevel + 4,
        tgLevel_SortType = tgLevel + 5,
        tgLevel_TotalCaption = tgLevel + 6,
        tgLevel_Filter = tgLevel + 7,
        tgLevel_Visible = tgLevel + 8,
        tgLevel_EOT = tgLevel + tgLast,

        tgFilter = tgStep * 82,
        tgFilter_BitmapURL = tgFilter + 1,
        tgFilter_Name = tgFilter + 2,
        tgFilter_Type = tgFilter + 3,
        tgFilter_Condition = tgFilter + 4,
        tgFilter_MeasureName = tgFilter + 5,
        tgFilter_FirstValue = tgFilter + 6,
        tgFilter_SecondValue = tgFilter + 7,
        tgFilter_LevelName = tgFilter + 8,
        tgFilter_EOT = tgFilter + tgLast,

        tgPagerSettings = tgStep * 83,
        tgPagerSettings_AllowPaging = tgPagerSettings + 1,
        tgPagerSettings_LinesInFrame = tgPagerSettings + 2,
        tgPagerSettings_EOT = tgPagerSettings + tgLast,

        tgIntelligence = tgStep * 84,
        tgIntelligence_MeasuresCount = tgIntelligence + 1,
        tgIntelligence_DisplayName = tgIntelligence + 2,
        tgIntelligence_Expression = tgIntelligence + 3,
        tgIntelligence_Type = tgIntelligence + 4,
        tgIntelligence_Group = tgIntelligence + 5,
        tgIntelligence_EOT = tgIntelligence + tgLast,

        tgDimension = tgStep * 85,
        tgDimension_NotVisible = tgDimension + 1,
        tgDimension_UniqueName = tgDimension + 2,
        tgDimension_Hierarchies = tgDimension + 3,
        tgDimension_EOT = tgDimension + tgLast,

        tgMeasureShowMode = tgStep * 86,
        tgMeasureShowMode_Mode = tgMeasureShowMode + 1,
        tgMeasureShowMode_Visible = tgMeasureShowMode + 2,
        tgMeasureShowMode_Caption = tgMeasureShowMode + 3,
        tgMeasureShowMode_UniqueName = tgMeasureShowMode + 4,
        tgMeasureShowMode_BitmapUrl = tgMeasureShowMode + 5,
        tgMeasureShowMode_EOT = tgMeasureShowMode + tgLast,

        tgMeasure = tgStep * 87,
        tgMeasure_UniqueName = tgMeasure + 1,
        tgMeasure_DefaultFormat = tgMeasure + 2,
        tgMeasure_Description = tgMeasure + 3,
        tgMeasure_DisplayFolder = tgMeasure + 4,
        tgMeasure_DisplayName = tgMeasure + 5,
        tgMeasure_Expression = tgMeasure + 6,
        tgMeasure_Function = tgMeasure + 7,
        tgMeasure_ID = tgMeasure + 8,
        tgMeasure_ShowModes = tgMeasure + 9,
        tgMeasure_Visible = tgMeasure + 10,
        tgMeasure_Filter = tgMeasure + 11,
        tgMeasure_NotVisibleInTree = tgMeasure + 12,
        tgMeasure_EOT = tgMeasure + tgLast,

        tgLayout = tgStep * 88,
        tgLayout_RowNodes = tgLayout + 1,
        tgLayout_ColumnNodes = tgLayout + 2,
        tgLayout_PageNodes = tgLayout + 3,
        tgLayout_RowAxis = tgLayout + 4,
        tgLayout_ColumnAxis = tgLayout + 5,
        tgLayout_PageAxis = tgLayout + 6,
        tgLayout_MeasureLayout = tgLayout + 7,
        tgLayout_MeasurePosition = tgLayout + 8,
        tgLayout_ShowMeasureIfPossible = tgLayout + 9,
        tgLayout_ShowMeasureModesIfPossible = tgLayout + 10,
        tgLayout_DetailsAxis = tgLayout + 11,
        tgLayout_XAxisMeasure = tgLayout + 12,
        tgLayout_YAxisMeasures = tgLayout + 13,
        tgLayout_ColorAxis = tgLayout + 14,
        tgLayout_SizeAxis = tgLayout + 15,
        tgLayout_ShapeAxis = tgLayout + 16,
        tgLayout_ColorForeAxis = tgLayout + 17,
        tgLayout_EOT = tgLayout + tgLast,

        tgOLAPGrid = tgStep * 89,
        tgOLAPGrid_Measures = tgOLAPGrid + 1,
        tgOLAPGrid_Dimensions = tgOLAPGrid + 2,
        tgOLAPGrid_Layout = tgOLAPGrid + 3,
        tgOLAPGrid_Mode = tgOLAPGrid + 4,
        tgOLAPGrid_Cellset = tgOLAPGrid + 5,
        tgOLAPGrid_Engine = tgOLAPGrid + 6,
        tgOLAPGrid_FilteredHierarchies = tgOLAPGrid + 8,
        tgOLAPGrid_XMLStream = tgOLAPGrid + 9,
        tgOLAPGrid_HierarchiesDisplayMode = tgOLAPGrid + 10,
        tgOLAPGrid_PivotingBehavior = tgOLAPGrid + 11,
        tgOLAPGrid_MaxTextLength = tgOLAPGrid + 12,
        tgOLAPGrid_AnalysisType = tgOLAPGrid + 13,
        tgOLAPGrid_FilterAreaVisible = tgOLAPGrid + 14,
        tgOLAPGrid_ShowAreasMode = tgOLAPGrid + 15,
        tgOLAPGrid_ShowModificationAreas = tgOLAPGrid + 16,
        tgOLAPGrid_ShowLegends = tgOLAPGrid + 17,
        tgOLAPGrid_IsSettingsEditable = tgOLAPGrid + 18,
        tgOLAPGrid_ShowToolbox = tgOLAPGrid + 19,
        tgOLAPGrid_ShowFilterGrid = tgOLAPGrid + 20,
        tgOLAPGrid_AllowScrolling = tgOLAPGrid + 21,
        tgOLAPGrid_StructureTreeWidth = tgOLAPGrid + 22,
        tgOLAPGrid_SupportEMail = tgOLAPGrid + 23,
        tgOLAPGrid_DelayPivoting = tgOLAPGrid + 25,
        tgOLAPGrid_UseFixedHeaders = tgOLAPGrid + 26,
        tgOLAPGrid_CallbackController = tgOLAPGrid + 27,
        tgOLAPGrid_CallbackAction = tgOLAPGrid + 28,
        tgOLAPGrid_ExportController = tgOLAPGrid + 29,
        tgOLAPGrid_ExportAction = tgOLAPGrid + 30,
        tgOLAPGrid_ClientLibPath = tgOLAPGrid + 31,
        tgOLAPGrid_Options = tgOLAPGrid + 32,
        tgOLAPGrid_Toolbox = tgOLAPGrid + 33,

        tgOLAPGrid_ChartsType = tgOLAPGrid + 34,

        tgOLAPGrid_JpegOptions = tgOLAPGrid + 35,
        tgOLAPGrid_PdfOptions = tgOLAPGrid + 36,
        tgOLAPGrid_XlsOptions = tgOLAPGrid + 37,
        tgOLAPGrid_XlsxOptions = tgOLAPGrid + 38,
        tgOLAPGrid_CsvOptions = tgOLAPGrid + 39,
        tgOLAPGrid_HtmlOptions = tgOLAPGrid + 40,

        tgOLAPGrid_AllowPaging = tgOLAPGrid + 41,
        tgOLAPGrid_EmptyCellString = tgOLAPGrid + 42,
        tgOLAPGrid_LinesInPage = tgOLAPGrid + 43,
        tgOLAPGrid_MaxRowsInGrid = tgOLAPGrid + 44,
        tgOLAPGrid_MaxColumnsInGrid = tgOLAPGrid + 45,
        tgOLAPGrid_UseCheckboxesInTree = tgOLAPGrid + 46,

        tgOLAPGrid_Height = tgOLAPGrid + 47,
        tgOLAPGrid_Width = tgOLAPGrid + 48,
        tgOLAPGrid_AllowDrilling = tgOLAPGrid + 49,
        tgOLAPGrid_AllowEditing = tgOLAPGrid + 50,
        tgOLAPGrid_AllowFiltering = tgOLAPGrid + 51,
        tgOLAPGrid_ClientCallbackFunction = tgOLAPGrid + 52,
        tgOLAPGrid_ErrorHandler = tgOLAPGrid + 53,
        tgOLAPGrid_MessageHandler = tgOLAPGrid + 54,

        tgOLAPGrid_ExpandDimensionsNode = tgOLAPGrid + 55,
        tgOLAPGrid_ExpandMeasuresNode = tgOLAPGrid + 56,
        tgOLAPGrid_HideDimensionNameIfPossible = tgOLAPGrid + 57,

        tgOLAPGrid_DrillthroughExportType = tgOLAPGrid + 58,
        tgOLAPGrid_IgnoreGridPaging = tgOLAPGrid + 59,

        tgOLAPGrid_CurrencyFormatString = tgOLAPGrid + 60,

        tgOLAPGrid_HierarchyEditorStyle = tgOLAPGrid + 62,

        tgOLAPGrid_AllowResizing = tgOLAPGrid + 63,
        tgOLAPGrid_AllowSelectionFormatting = tgOLAPGrid + 64,

        tgOLAPGrid_EOT = tgOLAPGrid + tgLast,

        tgCellset = tgStep * 90,
        tgCellset_OpenNodes = tgCellset + 1,
        tgCellset_ScrolledNodes = tgCellset + 2,
        tgCellset_SortingDirection = tgCellset + 3,
        tgCellset_SortedColumnIndex = tgCellset + 4,
        tgCellset_ExpandAllActions = tgCellset + 5,
        tgCellset_RowMetaMember = tgCellset + 6,
        tgCellset_ColMetaMember = tgCellset + 7,
        tgCellset_Comments = tgCellset + 8,
        tgCellset_DrillActions = tgCellset + 9,
        tgCellset_EOT = tgCellset + tgLast,

        tgRequest = tgStep * 91,
        tgRequest_Members = tgRequest + 1,
        tgRequest_Levels = tgRequest + 2,
        tgRequest_Measure = tgRequest + 3,
        tgRequest_MeasureMode = tgRequest + 4,
        tgRequest_EOT = tgRequest + tgLast,

        tgLine = tgStep * 92,
        tgLine_ID = tgLine + 1,
        tgLine_Measure = tgLine + 2,
        tgLine_Requests = tgLine + 3,
        tgLine_Mode = tgLine + 4,
        tgLine_CacheKey = tgLine + 5,
        tgLine_Depthes = tgLine + 6,
        tgLine_OriginalColumnType = tgLine + 7,
        tgLine_LineDataType = tgLine + 8,
        tgLine_CurrentMap = tgLine + 9,
        tgLine_HierID = tgLine + 10,

        tgMdLine_Indexes = tgLine + 11,
        tgMdLine_Data = tgLine + 12,

        tgLine_EOT = tgLine + tgLast,

        tgLineData = tgStep * 98,
        tgLineData_Value = tgLineData + 1,
        tgLineData_FormattedValue = tgLineData + 2,
        tgLineData_EOT = tgLineData + tgLast,

        tgMetaLine = tgStep * 93,
        tgMetaline_ID = tgMetaLine + 1,
        tgMetaline_Levels = tgMetaLine + 2,
        tgMetaline_IdxArray = tgMetaLine + 3,
        tgMetaline_HierArray = tgMetaLine + 4,
        tgMetaline_Lines = tgMetaLine + 5,
        tgMetaline_Limit = tgMetaLine + 6,
        tgMetaLine_EOT = tgMetaLine + tgLast,

        tgEngine = tgStep * 94,
        tgEngine_Levels = tgEngine + 1,
        tgEngine_Metalines = tgEngine + 2,
        tgEngine_EOT = tgEngine + tgLast,

        tgCubeDimension = tgStep * 95,
        tgCubeDimension_DisplayName = tgCubeDimension + 1,
        tgCubeDimension_UniqueName = tgCubeDimension + 2,
        tgCubeDimension_Description = tgCubeDimension + 3,
        tgCubeDimension_DimensionType = tgCubeDimension + 4,
        tgCubeDimension_Hierarchies = tgCubeDimension + 5,
        tgCubeDimension_KeyHierName = tgCubeDimension + 6,
        tgCubeDimension_EOT = tgCubeDimension + tgLast,

        tgMeasures = tgStep * 96,
        tgMeasures_MembersStream = tgMeasures + 1,
        tgMeasures_EOT = tgMeasures + tgLast,

        tgOLAPCube = tgStep * 97,
        tgOLAPCube_DataSet = tgOLAPCube + 1,
        tgOLAPCube_FactTableName = tgOLAPCube + 2,
        tgOLAPCube_Measures = tgOLAPCube + 3,
        tgOLAPCube_Dimensions = tgOLAPCube + 4,
        tgOLAPCube_LevelName = tgOLAPCube + 5,
        tgOLAPCube_InternalFactTable = tgOLAPCube + 6,
        tgOLAPCube_Active = tgOLAPCube + 7,
        tgOLAPCube_LevelsList = tgOLAPCube + 8,
        tgOLAPCube_EOT = tgOLAPCube + tgLast,

        tgCommonStream = tgStep * 100,
        tgCommonStream_ProductID = tgCommonStream + 1,
        tgCommonStream_VersionNumber = tgCommonStream + 2,
        tgCommonStream_CompressionMethod = tgCommonStream + 3,
        tgCommonStream_OLAPCube = tgCommonStream + 4,
        tgCommonStream_UserData = tgCommonStream + 5,
        tgCommonStream_GridState = tgCommonStream + 6,
        tgCommonStream_EOT = tgCommonStream + tgLast,

        tgASPGridSessionState = tgStep * 101,
        tgASPGridSessionState_CubeId = tgASPGridSessionState + 1,
        tgASPGridSessionState_Length = tgASPGridSessionState + 2,
        tgASPGridSessionState_Stream = tgASPGridSessionState + 3,
        tgASPGridSessionState_EOT = tgASPGridSessionState + tgLast,

        tgASPHierNode = tgStep * 102,
        tgASPHierNode_MemberName = tgASPHierNode + 1,
        tgASPHierNode_HasCustomMembers = tgASPHierNode + 2,
        tgASPHierNode_IsCustomMember = tgASPHierNode + 3,
        tgASPHierNode_Checked = tgASPHierNode + 4,
        tgASPHierNode_Expanded = tgASPHierNode + 5,
        tgASPHierNode_ParentName = tgASPHierNode + 6,
        tgASPHierNode_Children = tgASPHierNode + 7,
        tgASPHierNode_EOT = tgASPHierNode + tgLast,

        tgASPHierNodes = tgStep * 103,
        tgASPHierNodes_Count = tgASPHierNodes + 1,
        tgASPHierNodes_Frame1 = tgASPHierNodes + 2,
        tgASPHierNodes_Frame2 = tgASPHierNodes + 3,
        tgASPHierNodes_CurrentPage = tgASPHierNodes + 4,
        tgASPHierNodes_ItemsInPage = tgASPHierNodes + 5,
        tgASPHierNodes_TotalCount = tgASPHierNodes + 6,
        tgASPHierNodes_EOT = tgASPHierNodes + tgLast,

        tgASPHierEditor = tgStep * 104,
        tgASPHierEditor_FilterString = tgASPHierEditor + 1,
        tgASPHierEditor_HierarchyName = tgASPHierEditor + 2,
        tgASPHierEditor_Root = tgASPHierEditor + 3,
        tgASPHierEditor_ContextLevelName = tgASPHierEditor + 4,
        tgASPHierEditor_EOT = tgASPHierEditor + tgLast,

        tgMDCubeSessionState = tgStep * 105,
        tgMDCubeSessionState_Stream = tgMDCubeSessionState + 1,
        tgMDCubeSessionState_MDXSessionID = tgMDCubeSessionState + 2,
        tgMDCubeSessionState_EOT = tgMDCubeSessionState + tgLast,

        tgMeasureFilter = tgStep * 106,
        tgMeasureFilter_BitmapURL = tgMeasureFilter + 1,
        tgMeasureFilter_Condition = tgMeasureFilter + 2,
        tgMeasureFilter_FirstValue = tgMeasureFilter + 3,
        tgMeasureFilter_SecondValue = tgMeasureFilter + 4,
        tgMeasureFilter_RestrictsTo = tgMeasureFilter + 5,
        tgMeasureFilter_EOT = tgMeasureFilter + tgLast,

        tgPageState = tgStep * 107,
        tgPageState_Scale = tgPageState + 1,
        tgPageState_EOT = tgPageState + tgLast,

        tgLineMap = tgStep * 108,
        tgLineMap_Map = tgLineMap + 1,
        tgLineMap_EOT = tgLineMap + tgLast,

        tgMetaMember = tgStep * 109,
        tgMetaMember_Level = tgMetaMember + 1,
        tgMetaMember_Member = tgMetaMember + 2,
        tgMetaMember_Drilled = tgMetaMember + 3,
        tgMetaMember_EOT = tgMetaMember + tgLast,

        tgDataIndexBTree = tgStep * 110,

        tgExportOptions = tgStep * 111,
        tgExportOptions_ShowLegend = tgExportOptions + 1,
        tgExportOptions_LegendOrientation = tgExportOptions + 2,
        tgExportOptions_LegendPlacement = tgExportOptions + 3,
        tgExportOptions_PagePadding = tgExportOptions + 4,
        tgExportOptions_BGColor = tgExportOptions + 5,
        tgExportOptions_Border = tgExportOptions + 6,
        tgExportOptions_Unit = tgExportOptions + 7,
        tgExportOptions_WordWrap = tgExportOptions + 8,
        tgExportOptions_PageOrientation = tgExportOptions + 9,
        tgExportOptions_HierarchiesDisplayMode = tgExportOptions + 10,
        tgExportOptions_PageBreakeMode = tgExportOptions + 11,
        tgExportOptions_CellCaptionView = tgExportOptions + 12,
        tgExportOptions_CellMemberView = tgExportOptions + 13,
        tgExportOptions_CellMemberTotalView = tgExportOptions + 14,
        tgExportOptions_CellGroupView = tgExportOptions + 15,
        tgExportOptions_CellDataView = tgExportOptions + 16,
        tgExportOptions_CellDataTotalView = tgExportOptions + 17,
        tgExportOptions_EOT = tgExportOptions + tgLast,

        tgPadding = tgStep * 112,
        tgPadding_Top = tgPadding + 1,
        tgPadding_Bottom = tgPadding + 2,
        tgPadding_Left = tgPadding + 3,
        tgPadding_Right = tgPadding + 4,
        tgPadding_EOT = tgPadding + tgLast,

        tgToolboxButton = tgStep * 113,
        tgToolboxButton_Text = tgToolboxButton + 1,
        tgToolboxButton_ButtonID = tgToolboxButton + 2,
        tgToolboxButton_PressedText = tgToolboxButton + 3,
        tgToolboxButton_Image = tgToolboxButton + 4,
        tgToolboxButton_PressedImage = tgToolboxButton + 5,
        tgToolboxButton_Tooltip = tgToolboxButton + 6,
        tgToolboxButton_ClientScript = tgToolboxButton + 7,
        tgToolboxButton_IsPressed = tgToolboxButton + 8,
        tgToolboxButton_Visible = tgToolboxButton + 9,
        tgToolboxButton_NeedSeparator = tgToolboxButton + 10,
        tgToolboxButton_EOT = tgToolboxButton + tgLast,

        tgToolbox = tgStep * 114,
        tgToolbox_CustomButtons = tgToolbox + 1,
        tgToolbox_ConnectButton = tgToolbox + 2,
        tgToolbox_SaveLayoutButton = tgToolbox + 3,
        tgToolbox_LoadLayoutButton = tgToolbox + 4,
        tgToolbox_MDXQueryButton = tgToolbox + 5,
        tgToolbox_AddCalculatedMeasureButton = tgToolbox + 6,
        tgToolbox_ExportJPEGButton = tgToolbox + 7,
        tgToolbox_ExportCSVButton = tgToolbox + 8,
        tgToolbox_ExportXLSXButton = tgToolbox + 9,
        tgToolbox_ExportXLSButton = tgToolbox + 10,
        tgToolbox_ExportHTMLButton = tgToolbox + 11,
        tgToolbox_ExportPDFButton = tgToolbox + 12,
        tgToolbox_AllAreasButton = tgToolbox + 13,
        tgToolbox_ClearLayoutButton = tgToolbox + 14,
        tgToolbox_DataAreaButton = tgToolbox + 15,
        tgToolbox_PivotAreaButton = tgToolbox + 16,
        tgToolbox_ZoomOutButton = tgToolbox + 17,
        tgToolbox_ZoomInButton = tgToolbox + 18,
        tgToolbox_ResetZoomButton = tgToolbox + 19,
        tgToolbox_ModeButton = tgToolbox + 20,
        tgToolbox_DelayPivotingButton = tgToolbox + 21,
        tgToolbox_ResizingButton = tgToolbox + 22,
        tgToolbox_ButtonsOrder = tgToolbox + 23,
        tgToolbox_MeasurePlaceButton = tgToolbox + 24,
        tgToolbox_EOT = tgToolbox + tgLast,

        tgCellView = tgStep * 115,
        tgCellView_BackColor = tgCellView + 1,
        tgCellView_ForeColor = tgCellView + 2,
        tgCellView_Font = tgCellView + 3,
        tgCellView_AlignText = tgCellView + 4,
        tgCellView_AlignLine = tgCellView + 5,
        tgCellView_EOT = tgCellView + tgLast,
        tgDummy = tgStep * 255,

        tgJpegExportOptions = tgStep * 116,
        tgJpegExportOptions_Indent = tgJpegExportOptions + 1,
        tgJpegExportOptions_EOT = tgJpegExportOptions + tgLast,

        tgTextFormat = tgStep * 117,
        tgTextFormat_AlignText = tgTextFormat + 1,
        tgTextFormat_AlignLine = tgTextFormat + 2,
        tgTextFormat_ForeColor = tgTextFormat + 3,
        tgTextFormat_Text = tgTextFormat + 4,
        tgTextFormat_Font = tgTextFormat + 5,
        tgTextFormat_EOT = tgTextFormat + tgLast,

        tgExportOptionsPDF = tgStep * 118,
        tgExportOptionsPDF_Header = tgExportOptionsPDF + 1,
        tgExportOptionsPDF_PageNumber = tgExportOptionsPDF + 2,
        tgExportOptionsPDF_EOT = tgExportOptionsPDF + tgLast,

        tgExportOptionsXLS = tgStep * 119,
        tgExportOptionsXLS_PercentFormat = tgExportOptionsXLS + 1,
        tgExportOptionsXLS_NumberFormat = tgExportOptionsXLS + 2,
        tgExportOptionsXLS_FormatData = tgExportOptionsXLS + 3,
        tgExportOptionsXLS_WorkSheetNameFormat = tgExportOptionsXLS + 4,
        tgExportOptionsXLS_EOT = tgExportOptionsXLS + tgLast,

        tgExportOptionsHTML = tgStep * 120,
        tgExportOptionsHTML_Charset = tgExportOptionsHTML + 1,
        tgExportOptionsHTML_Title = tgExportOptionsHTML + 2,
        tgExportOptionsHTML_Border = tgExportOptionsHTML + 3,
        tgExportOptionsHTML_CellPadding = tgExportOptionsHTML + 4,
        tgExportOptionsHTML_CellSpacing = tgExportOptionsHTML + 5,
        tgExportOptionsHTML_EOT = tgExportOptionsHTML + tgLast,

        tgExportOptionsCSV = tgStep * 121,
        tgExportOptionsCSV_BreakSymbol = tgExportOptionsCSV + 1,
        tgExportOptionsCSV_EOT = tgExportOptionsCSV + tgLast,

        tgHierarchyEditorStyle = tgStep * 122,
        tgHierarchyEditorStyle_ItemsInPage = tgHierarchyEditorStyle + 1,
        tgHierarchyEditorStyle_Width = tgHierarchyEditorStyle + 2,
        tgHierarchyEditorStyle_TreeHeight = tgHierarchyEditorStyle + 3,
        tgHierarchyEditorStyle_Resizable = tgHierarchyEditorStyle + 4,
        tgHierarchyEditorStyle_EOT = tgHierarchyEditorStyle + tgLast
    }
}